apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: waterdeep
spec:
  containers:
  - image: nginx:1.27.4-alpine
    name: nginx
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
      readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: content
    configMap:
      name: nginx-config-html
status: {}
